### ISSUE TITLE
Mention MDSynthesis in your abstract

### ISSUE THREAD

**Issue by kain88-de** [datreant/scipy-2016#1]
You should show that this library already solves real problems for you and that other solutions can easily be build on top of it. I think that is one of the major selling points and another thing why datreant is much cooler then anything else out there.

**Comment by dotsdl** [comment]
Definitely. Especially since the project grew out of MDSynthesis to start, it makes complete sense to ground it with a more tangible example. I'll incorporate this.

**Comment by dotsdl** [comment]
Added in 6b705db4a404ae05a455c1979577f3e358fd9e70.
